### ISSUE TITLE
Look at/examine a door is not correctly handled

### ISSUE THREAD

**Issue by ruoyao-wang** [allenai/ScienceWorld#69] opened 2024-05-15 22:21 UTC
Taking an action to look at or examine a door gets the error "ERROR: SHOULD USE OVERRIDE FOR PORTAL."

**Comment by manatk** [comment] 2024-06-25 17:51
Bumping this - still isn't working!
<img width="491" alt="Screenshot 2024-06-25 at 10 50 51 AM" src="https://github.com/allenai/ScienceWorld/assets/37251821/fae7d4dd-4a52-44d5-b07c-0f5b132dc8b5">

**Comment by PeterAJansen** [comment] 2024-07-10 17:14
Fixed in #73

**Comment by MarcCote** [comment] 2024-07-10 17:21
A new release of ScienceWorld is available on Pypi. Feel free to re-open is the issue is not fully addressed.
https://github.com/allenai/ScienceWorld/releases/tag/1.2.1

**Closed by MarcCote** 2024-07-10 17:21 UTC
Labels: bug
